---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewall
data:
  rules.nft: |
    #!/usr/bin/nft -f
    flush ruleset

    table inet filter {
      chain input {
        type filter hook input priority 0; policy accept;

        icmp type echo-request counter
      }
    }

    # vim:set ts=2 sw=2 et:
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubewall
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubewall
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubewall
    spec:
      hostNetwork: true
      containers:
        - name: kubewall
          image: ghcr.io/devplayer0/kubewall:0.1.0
          imagePullPolicy: IfNotPresent
          args: [/run/nftables/rules.nft]
          securityContext:
            capabilities:
              add: [NET_ADMIN]
          volumeMounts:
            - name: rules
              mountPath: /run/nftables
      volumes:
        - name: rules
          configMap:
            name: kubewall
